channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cython
  - ipython
  - ipyparallel
  - ipywidgets
  - numpy
  - matplotlib
  - mpi4py
  - networkx
  - pandas
  - scikit-image
  - scikit-learn
  - sympy
  - plotly
  - seaborn
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - pip
  - pip:
    - japanize-matplotlib
